CREATE TABLE ENTITIES(EID IDENTITY PRIMARY KEY);

CREATE TABLE USERS(`UID` BIGINT PRIMARY KEY REFERENCES ENTITIES(EID), SEN BOOLEAN, NAME VARCHAR(255), PASS VARCHAR(255), BLOCK ARRAY REFERENCES ENTITIES(EID), SUBS ARRAY, SENT ARRAY, INBOX ARRAY);

CREATE TABLE GROUPS(GID BIGINT PRIMARY KEY REFERENCES ENTITIES(EID), NAME VARCHAR(255), CODE VARCHAR(255), DESC VARCHAR(255), STUDY BOOLEAN, PRIV BOOLEAN, `MOD` BOOLEAN, SUPG BIGINT REFERENCES GROUPS(GID), SUBG ARRAY REFERENCES GROUPS(GID), OWNER BIGINT REFERENCES USERS(UID), MEMB ARRAY REFERENCES USERS(UID));

CREATE TABLE MESSAGES(MID IDENTITY PRIMARY KEY, SUBJ VARCHAR(255), TEXT VARCHAR(255), ACPT BOOLEAN, TYPE TINYINT, AUTH BIGINT REFERENCES USERS(UID), `TO` BIGINT REFERENCES ENTITIES(EID));

ALTER TABLE USERS ADD FOREIGN KEY (SUBS) REFERENCES GROUPS(GID);
ALTER TABLE USERS ADD FOREIGN KEY (SENT) REFERENCES MESSAGES(MID);
ALTER TABLE USERS ADD FOREIGN KEY (INBOX) REFERENCES MESSAGES(MID);
