CREATE TABLE ENTITIES(EID IDENTITY PRIMARY KEY);

CREATE TABLE USERS(`UID` BIGINT PRIMARY KEY REFERENCES ENTITIES(EID), SEN BOOLEAN, NAME VARCHAR(255), PASS VARCHAR(255));

CREATE TABLE GROUPS(GID BIGINT PRIMARY KEY REFERENCES ENTITIES(EID), NAME VARCHAR(255), DESC VARCHAR(255), STUDY BOOLEAN, PRIV BOOLEAN, `MOD` BOOLEAN, OWNER BIGINT REFERENCES USERS(`UID`));

CREATE TABLE MESSAGES(MID IDENTITY PRIMARY KEY, TYPE TINYINT, SUBJ VARCHAR(255), TEXT VARCHAR(255), ACPT BOOLEAN, TIME TIMESTAMP, AUTH BIGINT REFERENCES USERS(UID), `TO` BIGINT REFERENCES ENTITIES(EID));

CREATE TABLE U_BLOCK(`UID` BIGINT REFERENCES USERS(`UID`), BLCK BIGINT REFERENCES ENTITIES(EID));

CREATE TABLE U_INBOX(`UID` BIGINT REFERENCES USERS(`UID`), MSG BIGINT REFERENCES MESSAGES(MID), READ BOOLEAN);

CREATE TABLE G_TREE(GID BIGINT REFERENCES GROUPS(GID), SUBG BIGINT REFERENCES GROUPS(GID));

CREATE TABLE G_MEMBERS(GID BIGINT REFERENCES GROUPS(GID), MEMB BIGINT REFERENCES USERS(`UID`));

CREATE TABLE M_REFS(MID BIGINT REFERENCES MESSAGES(MID), `REF` BIGINT);
